version: "3.9"
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: "start_alembic"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
      
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
